rails-amusement-park-v-000/config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'

  # sessions
  get '/signin', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  # users
  resources :users, except: [:index, :destroy]

  # attractions
  resources :attractions, except: [:destroy]

  # rides
  post '/rides/new', to: 'rides#new'

end

rails-amusement-park-v-000/app/models/attraction.rb
class Attraction < ActiveRecord::Base
  has_many :rides
  has_many :users, :through => :rides
end

rails-amusement-park-v-000/app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :attraction
  belongs_to :user

  def take_ride
    if too_short? && not_enough_tickets?
      "Sorry. " + ticket_issue + " " + height_issue
    elsif not_enough_tickets?
      "Sorry. " + ticket_issue
    elsif too_short?
      "Sorry. " + height_issue
    else
      current_tickets = user.tickets - attraction.tickets
      current_nausea = user.nausea + attraction.nausea_rating
      current_happiness = user.happiness + attraction.happiness_rating
      user.update(
        tickets: current_tickets,
        happiness: current_happiness,
        nausea: current_nausea
        )
      "Thanks for riding the #{attraction.name}!"
    end
  end
  
  def too_short?
    attraction.min_height > user.height
  end

  def not_enough_tickets?
    attraction.tickets > user.tickets
  end

  def ticket_issue
    "You do not have enough tickets to ride the #{attraction.name}."
  end

  def height_issue
    "You are not tall enough to ride the #{attraction.name}."
  end

end

rails-amusement-park-v-000/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :rides
  has_many :attractions, :through => :rides

  def mood
    if nausea < happiness
      'happy'
    else
      'sad'
    end
  end
end

rails-amusement-park-v-000/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :require_login, except: [:home, :new, :create]

  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to do that"
      redirect_to root_path
    end
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

rails-amusement-park-v-000/app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update]

  def index
    @attractions = Attraction.all
  end

  def show
  end

  def new
    @attraction = Attraction.new
  end

  def create
    @attraction = Attraction.new(attraction_params)
    if @attraction.save
      redirect_to attraction_path(@attraction)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @attraction.update(attraction_params)
      redirect_to attraction_path(@attraction)
    else
      render :edit
    end
  end

  private

  def attraction_params
    params.require(:attraction).permit(:name, :min_height, :happiness_rating, :nausea_rating, :tickets)
  end

  def set_attraction
    @attraction = Attraction.find_by(id: params[:id])
  end
end

rails-amusement-park-v-000/app/controllers/rides_controller.rb
class RidesController < ApplicationController
  
  def new
    ride = Ride.create(user: current_user, attraction_id: params[:attraction_id])
    redirect_to user_path(ride.user), alert: ride.take_ride
  end
end

rails-amusement-park-v-000/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(name: params[:user][:name])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "Welcome back, #{user.name}!"
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

rails-amusement-park-v-000/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :height, :happiness, :nausea, :tickets, :admin)
  end
end

rails-amusement-park-v-000/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

rails-amusement-park-v-000/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-amusement-park-v-000/app/helpers/attractions_helper.rb
module AttractionsHelper
end

rails-amusement-park-v-000/app/helpers/rides_helper.rb
module RidesHelper
end

rails-amusement-park-v-000/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails-amusement-park-v-000/app/helpers/users_helper.rb
module UsersHelper
end

rails-amusement-park-v-000/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails-amusement-park-v-000/app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %> <br>
  <%= f.text_field :name %> <br> </br>

  <%= f.label :password %> <br>
  <%= f.text_field :password %> <br> </br>

  <%= f.label "Height (in inches)" %> <br>
  <%= f.text_field :height %> <br> </br>

  <%= f.label "How happy are you? (1-5 scale)" %> <br>
  <%= f.text_field :happiness %> <br> </br>

  <%= f.label "How nauseous are you? (1-5 scale)" %> <br>
  <%= f.text_field :nausea %> <br> </br>

  <%= f.label "How many tickets do you want?" %> <br>
  <%= f.text_field :tickets %> <br> </br>

  <%= f.label "Check box if you are a theme park owner" %>
  <%= f.check_box :admin %> <br> </br>

  <%= f.submit %>
<% end %>

rails-amusement-park-v-000/app/views/users/edit.html.erb
<%= render 'users/form' %>

rails-amusement-park-v-000/app/views/users/new.html.erb
<%= render 'users/form' %>

rails-amusement-park-v-000/app/views/users/show.html.erb
<div class="info">
  <% if @user.admin %>
    <p><strong>ADMIN</strong></p>
  <% end %>
  <p><strong>Name:</strong> <%= @user.name %></p>
  <p><strong>Tickets:</strong> <%= @user.tickets %></p>
  <p><strong>Mood:</strong> <%= @user.mood %></p>
  <p><strong>Height:</strong> <%= @user.height %> inches</p>
  <p><%= link_to "Edit", edit_user_path(@user) %></p>
  <p><%= link_to "See Attractions", attractions_path %></p>
</div>